/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastroclientes;

/**
 *
 * @author robso
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        cadastrarCliente = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenu();
        acessarProdutos = new javax.swing.JMenuItem();
        cadastroEstoque = new javax.swing.JMenu();
        entradaEstoque = new javax.swing.JMenuItem();
        saidaEstoque = new javax.swing.JMenuItem();
        cadastrosControlesEstoque = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        acessoMateriais = new javax.swing.JMenuItem();
        controlFornecedor = new javax.swing.JMenu();
        acessoFornecedor = new javax.swing.JMenuItem();
        statusDaProducao = new javax.swing.JMenu();
        acessoProducao = new javax.swing.JMenuItem();
        tabelasPrecos = new javax.swing.JMenu();
        acessoTabelaPrecos = new javax.swing.JMenuItem();
        fecharMenus = new javax.swing.JMenu();
        sairMenus = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dream Menu");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastroclientes/tigre.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        menuClientes.setText("Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });

        cadastrarCliente.setForeground(new java.awt.Color(255, 102, 0));
        cadastrarCliente.setText("Acessar");
        cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteActionPerformed(evt);
            }
        });
        menuClientes.add(cadastrarCliente);

        jMenuBar1.add(menuClientes);

        menuProdutos.setText("Produtos");
        menuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutosActionPerformed(evt);
            }
        });

        acessarProdutos.setForeground(new java.awt.Color(255, 102, 0));
        acessarProdutos.setText("Acessar");
        acessarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessarProdutosActionPerformed(evt);
            }
        });
        menuProdutos.add(acessarProdutos);

        jMenuBar1.add(menuProdutos);

        cadastroEstoque.setText("Estoque");
        cadastroEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroEstoqueActionPerformed(evt);
            }
        });

        entradaEstoque.setForeground(new java.awt.Color(255, 102, 0));
        entradaEstoque.setText("Entrada");
        entradaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaEstoqueActionPerformed(evt);
            }
        });
        cadastroEstoque.add(entradaEstoque);

        saidaEstoque.setForeground(new java.awt.Color(255, 102, 0));
        saidaEstoque.setText("Saída");
        saidaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaEstoqueActionPerformed(evt);
            }
        });
        cadastroEstoque.add(saidaEstoque);

        cadastrosControlesEstoque.setForeground(new java.awt.Color(255, 102, 0));
        cadastrosControlesEstoque.setText("Cadastrar/Excluir");
        cadastrosControlesEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrosControlesEstoqueActionPerformed(evt);
            }
        });
        cadastroEstoque.add(cadastrosControlesEstoque);

        jMenuBar1.add(cadastroEstoque);

        jMenu1.setText("Matérias Primas");

        acessoMateriais.setForeground(new java.awt.Color(255, 102, 0));
        acessoMateriais.setText("Acesso");
        acessoMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessoMateriaisActionPerformed(evt);
            }
        });
        jMenu1.add(acessoMateriais);

        jMenuBar1.add(jMenu1);

        controlFornecedor.setText("Fornecedores");

        acessoFornecedor.setForeground(new java.awt.Color(255, 102, 0));
        acessoFornecedor.setText("Acesso");
        acessoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessoFornecedorActionPerformed(evt);
            }
        });
        controlFornecedor.add(acessoFornecedor);

        jMenuBar1.add(controlFornecedor);

        statusDaProducao.setText("Produção");

        acessoProducao.setForeground(new java.awt.Color(255, 102, 0));
        acessoProducao.setText("Acesso");
        acessoProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessoProducaoActionPerformed(evt);
            }
        });
        statusDaProducao.add(acessoProducao);

        jMenuBar1.add(statusDaProducao);

        tabelasPrecos.setText("Tabela Preços");

        acessoTabelaPrecos.setForeground(new java.awt.Color(255, 102, 0));
        acessoTabelaPrecos.setText("Acesso");
        acessoTabelaPrecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessoTabelaPrecosActionPerformed(evt);
            }
        });
        tabelasPrecos.add(acessoTabelaPrecos);

        jMenuBar1.add(tabelasPrecos);

        fecharMenus.setText("Fechar");

        sairMenus.setForeground(new java.awt.Color(255, 102, 0));
        sairMenus.setText("Sair Menu");
        sairMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenusActionPerformed(evt);
            }
        });
        fecharMenus.add(sairMenus);

        jMenuBar1.add(fecharMenus);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
        new Clientes().setVisible(true);
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutosActionPerformed
        
    }//GEN-LAST:event_menuProdutosActionPerformed

    private void acessarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessarProdutosActionPerformed
        new Principal().setVisible(true);
    }//GEN-LAST:event_acessarProdutosActionPerformed

    private void cadastroEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroEstoqueActionPerformed
        new ControleEstoque().setVisible(true);
    }//GEN-LAST:event_cadastroEstoqueActionPerformed

    private void entradaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaEstoqueActionPerformed
        new EntradaEstoque().setVisible(true);
    }//GEN-LAST:event_entradaEstoqueActionPerformed

    private void saidaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaEstoqueActionPerformed
        new SaidaEstoque().setVisible(true);
    }//GEN-LAST:event_saidaEstoqueActionPerformed

    private void acessoMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessoMateriaisActionPerformed
        new MateriaPrima().setVisible(true);
    }//GEN-LAST:event_acessoMateriaisActionPerformed

    private void cadastrosControlesEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrosControlesEstoqueActionPerformed
        new ControleEstoque().setVisible(true);
    }//GEN-LAST:event_cadastrosControlesEstoqueActionPerformed

    private void sairMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenusActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairMenusActionPerformed

    private void acessoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessoFornecedorActionPerformed
        new CadastrosFornecedores().setVisible(true);
    }//GEN-LAST:event_acessoFornecedorActionPerformed

    private void acessoProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessoProducaoActionPerformed
        new Producao().setVisible(true);
    }//GEN-LAST:event_acessoProducaoActionPerformed

    private void acessoTabelaPrecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessoTabelaPrecosActionPerformed
        new TabelasDePrecos().setVisible(true);
    }//GEN-LAST:event_acessoTabelaPrecosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acessarProdutos;
    private javax.swing.JMenuItem acessoFornecedor;
    private javax.swing.JMenuItem acessoMateriais;
    private javax.swing.JMenuItem acessoProducao;
    private javax.swing.JMenuItem acessoTabelaPrecos;
    private javax.swing.JMenuItem cadastrarCliente;
    private javax.swing.JMenu cadastroEstoque;
    private javax.swing.JMenuItem cadastrosControlesEstoque;
    private javax.swing.JMenu controlFornecedor;
    private javax.swing.JMenuItem entradaEstoque;
    private javax.swing.JMenu fecharMenus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenuItem saidaEstoque;
    private javax.swing.JMenuItem sairMenus;
    private javax.swing.JMenu statusDaProducao;
    private javax.swing.JMenu tabelasPrecos;
    // End of variables declaration//GEN-END:variables
}
